### ISSUE TITLE
pip install leaves out wext_style.mplstyle

### ISSUE THREAD

**Issue by mperrin** [JarronL/webbpsf_ext#14]
Reported by @kglidic and reproduced by me. 

The file `[wext_style.mplstyle](https://github.com/JarronL/webbpsf_ext/blob/develop/webbpsf_ext/wext_style.mplstyle)` is not being installed correctly by `pip`. It's being left out or not downloaded. It works if installed by `git clone`, but not by `pip install`. 

My guess is this is because it's not a .py file, so by default `pip` is not installing it.

**Comment by mperrin** [comment]
See https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html for Setuptools docs on "Controlling files in the distribution"

**Comment by kglidic** [comment]
The default way that `webbpsf_ext` is installed alongside `spaceKLIP` is through `pip` install. However, this method does not download a file named wext_style.mplstyle, which can cause some functions in `spaceKLIP` to crash.

Quick Fix for `spaceKLIP` Users:
1. Download the required file from this link: [wext_style.mplstyle](https://github.com/JarronL/webbpsf_ext/blob/develop/webbpsf_ext/wext_style.mplstyle).
2. Locate where the `webbpsf_ext` package is installed by running: `pip show webbpsf_ext`
3. Once you identify the installation directory, copy the downloaded file into the `webbpsf_ext` directory.

Alternatively, performing a `git clone` of the `webbpsf_ext` repository will include all the necessary files.

**Comment by JarronL** [comment]
Thanks! I have added it to the manifest and will shortly push a minor update to pip!
