### ISSUE TITLE
path joining bug in bandpasses.py line 52

### ISSUE THREAD

**Issue by aggle** [JarronL/webbpsf_ext#5]
Line 57 in `bandpasses.py` (`hdulist = fits.open(filt_dir + fname)`) is throwing an error for me because of a missing slash:
```
FileNotFoundError: [Errno 2] No such file or directory: '/grp/jwst/ote/webbpsf-dataMIRI/filters/F1550C_throughput.fits'
```
The source of the error is on Line 52: `filt_dir = webbpsf.utils.get_webbpsf_data_path() + 'MIRI/filters/'`

Both lines could probably use a call to `os.path.join` (or `pathlib.Path`), as in `hdulist = fits.open(os.path.join(filt_dir, fname))`

**Comment by JarronL** [comment]
Fixed in PR #6.
